- id: '1586380930971'
  alias: Turn purifier off when any window is open
  description: ''
  trigger:
  - device_id: a363125c98ff4cb09312794c6dfb926c
    domain: binary_sensor
    entity_id: binary_sensor.door_balcony
    for:
      hours: 0
      minutes: 0
      seconds: 5
    platform: device
    type: opened
  - device_id: b58fe725fac34b26a4e56dc995f5e1f5
    domain: binary_sensor
    entity_id: binary_sensor.window_kitchen
    for:
      hours: 0
      minutes: 0
      seconds: 5
    platform: device
    type: opened
  - device_id: f4c16952358740fd8533a64fa9b21d50
    domain: binary_sensor
    entity_id: binary_sensor.window_bedroom
    for:
      hours: 0
      minutes: 0
      seconds: 5
    platform: device
    type: opened
  condition:
  - condition: state
    entity_id: switch.socket_purifier
    state: 'on'
  action:
  - data: {}
    entity_id: switch.socket_purifier
    service: switch.turn_off
- id: '1586381806258'
  alias: Turn purifier on when all windows are closed
  description: ''
  trigger:
  - device_id: b58fe725fac34b26a4e56dc995f5e1f5
    domain: binary_sensor
    entity_id: binary_sensor.window_kitchen
    for:
      hours: 0
      minutes: 0
      seconds: 5
    platform: device
    type: not_opened
  - device_id: f4c16952358740fd8533a64fa9b21d50
    domain: binary_sensor
    entity_id: binary_sensor.window_bedroom
    for:
      hours: 0
      minutes: 0
      seconds: 5
    platform: device
    type: not_opened
  - device_id: a363125c98ff4cb09312794c6dfb926c
    domain: binary_sensor
    entity_id: binary_sensor.door_balcony
    for:
      hours: 0
      minutes: 0
      seconds: 5
    platform: device
    type: not_opened
  condition:
  - condition: and
    conditions:
    - condition: device
      device_id: f4c16952358740fd8533a64fa9b21d50
      domain: binary_sensor
      entity_id: binary_sensor.window_bedroom
      for:
        hours: 0
        minutes: 0
        seconds: 0
      type: is_not_open
    - condition: device
      device_id: b58fe725fac34b26a4e56dc995f5e1f5
      domain: binary_sensor
      entity_id: binary_sensor.window_kitchen
      type: is_not_open
    - condition: device
      device_id: a363125c98ff4cb09312794c6dfb926c
      domain: binary_sensor
      entity_id: binary_sensor.door_balcony
      type: is_not_open
    - condition: state
      entity_id: switch.socket_purifier
      state: 'off'
  action:
  - data: {}
    entity_id: switch.socket_purifier
    service: switch.turn_on
- id: '1586383036124'
  alias: Turn on gateway light when motion detected
  description: ''
  trigger:
  - device_id: a3bc7980f4064d778270089a992e3f75
    domain: binary_sensor
    entity_id: binary_sensor.motion_hall
    platform: device
    type: motion
  condition:
  - condition: or
    conditions:
    - after: sunset
      condition: sun
    - before: sunrise
      condition: sun
  action:
  - data: {}
    entity_id: light.gateway_aqara
    service: light.turn_on
- id: '1586383184595'
  alias: Turn off gateway light when no motion detected
  description: ''
  trigger:
  - device_id: a3bc7980f4064d778270089a992e3f75
    domain: binary_sensor
    entity_id: binary_sensor.motion_hall
    for:
      hours: 0
      minutes: 0
      seconds: 30
    platform: device
    type: no_motion
  condition:
  - condition: or
    conditions:
    - after: sunset
      condition: sun
    - before: sunrise
      condition: sun
  action:
  - data: {}
    entity_id: light.gateway_aqara
    service: light.turn_off
- id: '1586635488797'
  alias: Scheduled cleaning
  description: ''
  trigger:
  - at: '6:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.start
- id: '1586635940566'
  alias: Start cleaning using cube
  description: ''
  trigger:
  - event_data:
      action_type: flip90
      entity_id: binary_sensor.cube
    event_type: xiaomi_aqara.cube_action
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.start
- id: '1586636451206'
  alias: Stop cleaning using cube
  description: ''
  trigger:
  - event_data:
      action_type: flip180
      entity_id: binary_sensor.cube
    event_type: xiaomi_aqara.cube_action
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.stop
  - data: {}
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.return_to_base
