homeassistant:
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

# hacs:
#   token: !secret hacs_token

airly:
    api_key: !secret airly_key

logger:
    default: warn
    logs:
      custom_components.mitemp_bt: info

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_gateway_key

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

light:
  - platform: xiaomi_miio
    name: Desk lamp
    host: !secret xiaomi_desk_lamp_ip
    token: !secret xiaomi_desk_lamp_token
    model: philips.light.sread1

sensor:
  - platform: mitemp_bt
    rounding: True
    decimals: 1
    period: 60
    log_spikes: False
    use_median: False
    active_scan: False
    hci_interface: 0
    batt_entities: True
    report_unknown: False
  - platform: impk
    stops:
      - id: 17118
        name: marchewkowa_from_krzyki
        lines:
          - "107"
      - id: 17117
        name: marchewkowa_to_krzyki
        lines:
          - "D"
          - "107"
      - id: 16410
        name: klecina_to_krzyki
        lines:
          - "7"
          - "17"
  - platform: waze_travel_time
    origin: zone.home
    destination: "51.1091861,17.0369286"
    name: Do pracy
    region: 'EU'
  - platform: waze_travel_time
    origin: "51.1091861,17.0369286"
    destination: zone.home
    name: Z pracy
    region: 'EU'

sonoff:
    username: !secret sonoff_username
    password: !secret sonoff_password
    scan_interval: 60
    grace_period: 600
    api_region: 'eu'
    entity_prefix: True
    debug: False

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 48

device_tracker:
  - platform: huawei_router
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    consider_home: 60
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
